name: LinuxRunner

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Running your Shell Script.
      - name: Run a one-line script
        run: sudo bash runme.sh

